left_arm/controller_joint_names: ['LARM_JOINT0','LARM_JOINT1','LARM_JOINT2','LARM_JOINT3','LARM_JOINT4','LARM_JOINT5']
right_arm/controller_joint_names: ['RARM_JOINT0','RARM_JOINT1','RARM_JOINT2','RARM_JOINT3','RARM_JOINT4','RARM_JOINT5']
head/controller_joint_names: ['HEAD_JOINT0','HEAD_JOINT1']
chest/controller_joint_names: ['CHEST_JOINT0']